name: ✨ Feature Request
description: Suggest a new feature for the Darkman Theme
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        🦇 **Help make the Darkman Theme even better!**
        
        Share your ideas for new features or improvements.
        
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature is this?
      options:
        - New color scheme variation
        - UI/UX improvement
        - Language support enhancement
        - Accessibility improvement
        - Developer experience improvement
        - Other
    validations:
      required: true
      
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the feature you'd like to see
      placeholder: Add support for...
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve? What's the use case?
      placeholder: Currently, when I'm coding at night...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: I would like the theme to...
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      
  - type: textarea
    id: batman-connection
    attributes:
      label: Batman Theme Connection
      description: How does this feature align with the Batman/Batcomputer aesthetic?
      placeholder: This would make coding feel more like using the Batcomputer because...
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'd be willing to help implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, mockups, or examples